### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by thm-unix** [kbumsik/VirtScreen#106]
# Bug report
## Short description
Doesn't run.
### How do you reproduce the bug?
Try to run the application. Tried both AppImage and Python module. Says different errors.
When I try to start it as Python module, it says:

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/virtscreen-0.3.1-py3.10.egg/virtscreen/__main__.py", line 25, in <module>
    from quamash import QEventLoop
  File "/usr/lib/python3.10/site-packages/Quamash-0.6.1-py3.10.egg/quamash/__init__.py", line 594, in <module>
    from ._unix import _SelectorEventLoop
  File "/usr/lib/python3.10/site-packages/Quamash-0.6.1-py3.10.egg/quamash/_unix.py", line 44, in <module>
    class _SelectorMapping(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'`

When I try to start it as AppImage:
it starts, but when I click on tray icon, it crashes saying:
`
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
/tmp/.mount_VirtScNqJX7d/AppRun: line 14: 10795 Aborted                 (core dumped) $ENV/bin/python3 $ENV/bin/virtscreen $@
`

## Suggestion of solution
For the Python package, I guess, this problem started when Python 3.10 was released. I used this app before with Python 3.9.
For the AppImage, I suggest you to use *.ui files and uic.loadUi(filename) for form design. It works better.

## Additional Info
My distro is <b>Arch Linux</b>
Python version is <b>3.10.1</b>

**Comment by iCodePoet** [comment]
Same issue. any update?
